spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdb
    username: puser
    password: ppassword
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core: DEBUG